/**
 * This code was generated by "react-native codegen-harmony"
 * 
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 * 
 * @generatorVersion: 1
 */


#include "IdoModule.h"

namespace rnoh {
using namespace facebook;

IdoModule::IdoModule(const ArkTSTurboModule::Context ctx, const std::string name) : ArkTSTurboModule(ctx, name) {
    methodMap_ = {
        ARK_METHOD_METADATA(startSdk, 2),
        ARK_METHOD_METADATA(gtcid, 1),
        ARK_METHOD_METADATA(version, 1),
        ARK_METHOD_METADATA(setDebugEnable, 1),
        ARK_METHOD_METADATA(setSessionTime, 1),
        ARK_METHOD_METADATA(setMinAppActiveDuration, 1),
        ARK_METHOD_METADATA(setMaxAppActiveDuration, 1),
        ARK_METHOD_METADATA(setEventUploadInterval, 1),
        ARK_METHOD_METADATA(setEventForceUploadSize, 1),
        ARK_METHOD_METADATA(setProfileUploadInterval, 1),
        ARK_METHOD_METADATA(setProfileForceUploadSize, 1),
        ARK_METHOD_METADATA(setUserId, 1),
        ARK_METHOD_METADATA(trackCustomKeyValueEventBegin, 1),
        ARK_METHOD_METADATA(trackCustomKeyValueEventEnd, 3),
        ARK_METHOD_METADATA(trackCountEvent, 3),
        ARK_METHOD_METADATA(setProfile, 2),
    };
}

} // namespace rnoh

